### ISSUE TITLE
Add description to package.json

### ISSUE THREAD

**Issue by fisker** [glimmerjs/glimmer-vm#1750]
Packages like [`@glimmer/syntax`](https://github.com/glimmerjs/glimmer-vm/blob/main/packages/%40glimmer/syntax/package.json) missing `description` field.

**Comment by kategengler** [comment]
We have merged this repo with https://github.com/emberjs/ember.js/ and will no longer be publishing these packages separately.

**Comment by fisker** [comment]
Wow, how will this affect Prettier? Do we still have access to the functionalities Prettier needs?

**Comment by kategengler** [comment]
Sorry I'm copy & pasting. @glimmer/syntax will be one of the few that will continue to publish, but from emberjs/ember.js

**Comment by fisker** [comment]
Thanks!
