### ISSUE TITLE
Using Custom Elements is broken since Glimmer v0.22.0

### ISSUE THREAD

**Issue by dunnkers** [glimmerjs/glimmer-vm#453]
## Problem
Since Glimmer v0.22.0 using custom elements created with Polymer nested inside each other does not work.

My addon [ember-polymer](https://github.com/dunnkers/ember-polymer) did not pass tests since _ember 2.13.0-beta.1_. All the tests basically do is try to render a custom element and check whether it was successful. I noticed the cause was the upgrade to _Glimmer v0.22.0_, since the errors are thrown by glimmer code. The error occurs only when custom elements are nested inside each other.

## Reproduction
Ember Twiddle does not work with beta versions of ember. Therefore I created a repository called [glimmer-bug-example](https://github.com/dunnkers/glimmer-bug-example) to show the error.

**Using ember v2.12.0** (glimmer < v0.22.0)
![screen shot 2017-04-03 at 16 52 24](https://cloud.githubusercontent.com/assets/744430/24615339/45648956-188e-11e7-9cd3-7e532a6dd34e.png)
([master](https://github.com/dunnkers/glimmer-bug-example/tree/master) branch)

**Using ember v2.13.0-beta.1** (glimmer ^ v0.22.0)
![screen shot 2017-04-03 at 16 54 13](https://cloud.githubusercontent.com/assets/744430/24615345/4a2981da-188e-11e7-9a61-571b7325c6f3.png)
[full error log](https://gist.github.com/dunnkers/88f5aa5c99a81153edc583a652e9cd99)
([ember-beta](https://github.com/dunnkers/glimmer-bug-example/tree/ember-beta) branch)

This error does though, only occur when **nesting** custom elements. Just using custom elements is just fine:

![screen shot 2017-04-03 at 16 59 59](https://cloud.githubusercontent.com/assets/744430/24615630/17a8e146-188f-11e7-8aeb-e1365d1b7c89.png)

## Solving this problem
It would be great if someone takes a look at this! I think there might be some conflicting mechanisms in Glimmer's DOM processing and in the custom elements spec.

**Comment by rwjblue** [comment]
Thank you for the detailed bug report and digging that you have done to track this down!

**Comment by rwjblue** [comment]
Looks like we do not register a statement for `Component` wireformat opcode (which is number 9 in [this enum](https://github.com/tildeio/glimmer/blob/v0.22.0/packages/%40glimmer/wire-format/lib/opcodes.ts#L12)) [here](https://github.com/tildeio/glimmer/blob/v0.22.0/packages/%40glimmer/runtime/lib/syntax/functions.ts#L100-L261).

I'm not quite sure of the right implementation for it, but that seems to be the issue.

@chadhietala - Do you have an idea on what the implementation should be?

**Comment by JackCA** [comment]
just hit this issue as well -- let me know if I can provide any additional context that would be helpful

**Comment by rwjblue** [comment]
@JackCA - You hit this in Ember 2.13?

**Comment by JackCA** [comment]
@rwjblue yessir

**Comment by JackCA** [comment]
@rwjblue let me know if I can provide any specific information that will help. I'm using a combination of tagless and custom-tag components

**Comment by backspace** [comment]
This has also [broken `ember-paper` for me on Ember 2.13](https://github.com/miguelcobain/ember-paper/issues/705), specifically the `paper-chips` component. After updating, the main content area of my application wasn’t rendering, with this error in the console:

`ember.debug.js:19829 Error: expected an implementation for 6`
<details>
<summary>Stacktrace</summary>
<pre>
    at Object.debugAssert [as assert] (ember.debug.js:1498)
    at Compilers.compile (ember.debug.js:1201)
    at compileStatement (ember.debug.js:1200)
    at ember.debug.js:1200
    at Array.forEach (<anonymous>)
    at WrappedBuilder.compile (ember.debug.js:1200)
    at ComponentLayoutBuilder.compile (ember.debug.js:1173)
    at Object.compileLayout (ember.debug.js:1173)
    at Cache._emberMetal.Cache.owner [as func] (ember.debug.js:11330)
    at Cache.get (ember.debug.js:18578)
</pre>
</details>

Thanks to @rwjblue’s [suggestion](https://embercommunity.slack.com/archives/C06JXEHU7/p1493690508281497) on the Ember Community Slack, I changed the [relevant template](https://github.com/miguelcobain/ember-paper/blob/f07be761164cc97b55e2fa4ae45703e6619c9d4b/addon/templates/components/paper-chips.hbs#L1-L8) from having `md-chips-wrap` and `md-chip` elements to have `div`s instead and the error disappeared.

If there’s any additional information that would be helpful for me to share here, let me know!

**Comment by kellyselden** [comment]
I'm also getting this with an A-Frame project in 2.12 => 2.13:

```hbs
<a-scene>
  <a-assets>
    <a-asset-item id="headObj" src="{{rootURL}}tex.obj"></a-asset-item>
    <a-asset-item id="headMtl" src="{{rootURL}}tex.mtl"></a-asset-item>
  </a-assets>

  {{! more stuff }}

</a-scene>
```

The error is:

```
ember.debug.js:19829 Error: expected an implementation for 9
    at Object.debugAssert [as assert] (http://localhost:4200/assets/vendor.js:12742:19)
    at Compilers.compile (http://localhost:4200/assets/vendor.js:12445:465)
    at compileStatement (http://localhost:4200/assets/vendor.js:12444:8728)
```

**Comment by krisselden** [comment]
Someone mind opening an issue on ember regarding the regression in 2.13? Also, we are working on this, it's just a bit involved.

**Comment by rwjblue** [comment]
Fixed by https://github.com/glimmerjs/glimmer-vm/pull/488.

**Comment by dunnkers** [comment]
Great work @rwjblue and @krisselden !

**Comment by bjornharrtell** [comment]
While this fixes `Error: expected an implementation for 9` you can still get `Error: expected an implementation for 6`. Is this expected error and something that needs be fixed at application level?

Noted in the attempted upgrade for `ember-paper` here https://github.com/miguelcobain/ember-paper/pull/709.

@backspace described the problem above involving `paper-clips`.

**Comment by rwjblue** [comment]
@bjornharrtel - please open issues for each of those, we'll need template snippets that cause them to be able to fix...

**Comment by bjornharrtell** [comment]
@rwjblue great to hear that. I've opened https://github.com/emberjs/ember.js/issues/15258 with two separate jsbin template snippets that demonstrate additional issues.
